#!/bin/bash -e

psql -v ON_ERROR_STOP=1 --username postgres --dbname postgres <<-EOSQL

  CREATE USER "$SENDER_USER" PASSWORD '$SENDER_PASSWORD';
  CREATE DATABASE "$SENDER_DB";
  GRANT CONNECT ON DATABASE "$SENDER_DB" TO "$SENDER_USER";

EOSQL

psql -v ON_ERROR_STOP=1 --username postgres --dbname "$SENDER_DB" <<-EOSQL

  CREATE SCHEMA "$SENDER_SCHEMA" AUTHORIZATION "$SENDER_USER";

  GRANT ALL PRIVILEGES ON SCHEMA "$SENDER_SCHEMA" TO "$SENDER_USER";
  GRANT USAGE ON SCHEMA "$SENDER_SCHEMA" TO "$SENDER_USER";
  GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA "$SENDER_SCHEMA" TO "$SENDER_USER";
  GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA "$SENDER_SCHEMA" TO "$SENDER_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$SENDER_DB" TO "$SENDER_USER";

EOSQL