
spring:
  application:
    name:  telegram-sender
  datasource:
    url: ${SENDER_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SENDER_DATABASE_USERNAME}
    password: ${SENDER_DATABASE_PASSWORD}
    hikari:
      schema: ${SENDER_DATABASE_SCHEMA}
      minimum-idle: 2
      maximum-pool-size: 20
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: ${SENDER_DATABASE_SCHEMA}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        default_schema: ${SENDER_DATABASE_SCHEMA}
      jdbc:
        lob:
          non_contextual_creation: true
server:
  port: 8081
